package middleware

import (
	"encoding/json"
	"io"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gofiber/fiber/v2"
)

// --- ClassifyEUAIActRisk unit tests ---

func TestClassify_Unacceptable_SocialCreditScore(t *testing.T) {
	result := ClassifyEUAIActRisk("Build a social credit score system for citizens")
	if result.RiskLevel != AIActUnacceptable {
		t.Errorf("expected unacceptable, got %s", result.RiskLevel)
	}
}

func TestClassify_High_EmploymentScreening(t *testing.T) {
	result := ClassifyEUAIActRisk("Use AI for hiring decision and recruitment screening of job applicants")
	if result.RiskLevel != AIActHigh {
		t.Errorf("expected high, got %s", result.RiskLevel)
	}
	foundEmployment := false
	for _, r := range result.Reasons {
		if strings.Contains(r, "employment") {
			foundEmployment = true
		}
	}
	if !foundEmployment {
		t.Errorf("expected employment reason, got %v", result.Reasons)
	}
}

func TestClassify_High_MedicalDiagnosis(t *testing.T) {
	result := ClassifyEUAIActRisk("Provide a medical diagnosis and treatment recommendation for the patient")
	if result.RiskLevel != AIActHigh {
		t.Errorf("expected high, got %s", result.RiskLevel)
	}
}

func TestClassify_Limited_Chatbot(t *testing.T) {
	result := ClassifyEUAIActRisk("This chatbot virtual assistant handles customer queries")
	if result.RiskLevel != AIActLimited {
		t.Errorf("expected limited, got %s", result.RiskLevel)
	}
}

func TestClassify_Minimal_DocumentSummary(t *testing.T) {
	result := ClassifyEUAIActRisk("Summarize this document for me please")
	if result.RiskLevel != AIActMinimal {
		t.Errorf("expected minimal, got %s", result.RiskLevel)
	}
}

// --- Middleware integration tests ---

func newTestApp(siemChan chan<- SIEMEvent) *fiber.App {
	app := fiber.New()
	app.Use(NewEUAIActMiddleware(siemChan))
	app.Post("/v1/chat", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	})
	return app
}

func TestMiddleware_BlocksUnacceptable(t *testing.T) {
	app := newTestApp(nil)

	req := httptest.NewRequest("POST", "/v1/chat", strings.NewReader(`{"messages":[{"content":"implement a social credit score system"}]}`))
	req.Header.Set("Content-Type", "application/json")

	resp, err := app.Test(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != fiber.StatusForbidden {
		t.Errorf("expected 403, got %d", resp.StatusCode)
	}

	body, _ := io.ReadAll(resp.Body)
	var payload map[string]any
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatalf("response is not valid JSON: %v", err)
	}
	errObj, ok := payload["error"].(map[string]any)
	if !ok {
		t.Fatal("missing error object in response")
	}
	if errObj["type"] != "eu_ai_act_prohibited" {
		t.Errorf("expected type eu_ai_act_prohibited, got %v", errObj["type"])
	}
}

func TestMiddleware_SetsRiskHeader_AllLevels(t *testing.T) {
	cases := []struct {
		body     string
		expected string
	}{
		{`{"messages":[{"content":"summarize this document"}]}`, "minimal"},
		{`{"messages":[{"content":"chatbot virtual assistant"}]}`, "limited"},
		{`{"messages":[{"content":"medical diagnosis recommendation"}]}`, "high"},
	}

	for _, tc := range cases {
		app := newTestApp(nil)
		req := httptest.NewRequest("POST", "/v1/chat", strings.NewReader(tc.body))
		req.Header.Set("Content-Type", "application/json")

		resp, err := app.Test(req)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()

		got := resp.Header.Get("X-EU-AI-Act-Risk")
		if got != tc.expected {
			t.Errorf("body=%q: expected X-EU-AI-Act-Risk=%s, got %s", tc.body, tc.expected, got)
		}
	}
}

func TestMiddleware_SetsDisclosureHeader_Limited(t *testing.T) {
	app := newTestApp(nil)

	req := httptest.NewRequest("POST", "/v1/chat", strings.NewReader(`{"messages":[{"content":"chatbot virtual assistant reply"}]}`))
	req.Header.Set("Content-Type", "application/json")

	resp, err := app.Test(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()

	got := resp.Header.Get("X-AI-Disclosure")
	expected := "This response is generated by AI"
	if got != expected {
		t.Errorf("expected X-AI-Disclosure=%q, got %q", expected, got)
	}
}
